from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import database


def generate_pdf_report(filepath="soc_report.pdf"):
    doc = SimpleDocTemplate(filepath, pagesize=LETTER)
    story = []
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=30
    )

    story.append(Paragraph("SOC Threat Report", title_style))

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    story.append(Paragraph(f"Generated: {timestamp}", styles["Normal"]))
    story.append(Spacer(1, 20))

    alerts = database.get_all_alerts_for_report()

    stats = database.get_alert_stats()

    story.append(Paragraph("Summary", styles["Heading2"]))

    summary_data = [
        ["Metric", "Value"],
        ["Total Alerts", str(stats["total_today"])],
    ]

    for severity in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        count = stats["by_severity"].get(severity, 0)
        summary_data.append([severity, str(count)])

    summary_table = Table(summary_data, colWidths=[2*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16213e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f1f1f1")),
        ("GRID", (0, 0), (-1, -1), 1, colors.black)
    ]))

    story.append(summary_table)
    story.append(Spacer(1, 20))

    if stats["top_ips"]:
        story.append(Paragraph("Top Attacking IPs", styles["Heading2"]))

        ip_data = [["IP", "Count"]]
        for ip, count in stats["top_ips"]:
            ip_data.append([ip, str(count)])

        ip_table = Table(ip_data, colWidths=[3*inch, 1*inch])
        ip_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16213e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
            ("BACKGROUND", (0, 1), (-1, -1), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black)
        ]))

        story.append(ip_table)
        story.append(Spacer(1, 20))

    if alerts:
        story.append(Paragraph("Alert Details", styles["Heading2"]))

        alert_data = [["Timestamp", "Type", "IP", "Severity", "Details"]]

        for alert in alerts[:50]:
            timestamp = alert[1][:19]
            threat_type = alert[2]
            ip = alert[3] or "-"
            severity = alert[4]
            details = (alert[5] or "")[:40]

            alert_data.append([timestamp, threat_type, ip, severity, details])

        alert_table = Table(alert_data, colWidths=[1.5*inch, 1*inch, 1.2*inch, 0.8*inch, 2*inch])

        def get_severity_color(sev):
            return {
                "CRITICAL": colors.red,
                "HIGH": colors.HexColor("#ff6600"),
                "MEDIUM": colors.yellow,
                "LOW": colors.green
            }.get(sev, colors.black)

        alert_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16213e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("BACKGROUND", (0, 1), (-1, -1), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")])
        ]))

        story.append(alert_table)

    story.append(Spacer(1, 30))

    footer_style = ParagraphStyle("Footer", fontSize=10, textColor=colors.gray, alignment=1)
    story.append(Paragraph("Generated by Sentinel-SOC Dashboard", footer_style))

    doc.build(story)
    return filepath